In [32]:
import torch
import numpy as np

In [3]:
torch.FloatTensor([5,10])

tensor([ 5., 10.])

In [4]:
a=torch.FloatTensor([5,10])
b=torch.FloatTensor([12,10])

In [5]:
a+b

tensor([17., 20.])

In [17]:
torch.randint(0,2,size=(2,2))

tensor([[0., 0.],
        [0., 0.]])

In [22]:
matrix = torch.randn(5,5)

In [20]:
torch.randn_like(b)

tensor([-1.0146, -0.6289])

In [24]:
matrix

tensor([[-0.2987,  1.7304,  1.0786,  0.3269,  0.3150],
        [-0.7260, -0.4039, -0.9133, -1.5277,  0.9224],
        [ 0.8402,  0.4706,  0.9419,  0.1316, -0.4039],
        [-0.5339,  0.6470, -0.0164, -1.0129,  1.6617],
        [-0.2885,  0.9951,  1.1941,  0.5672,  0.8221]])

In [26]:
matrix.t()

tensor([[-0.2987, -0.7260,  0.8402, -0.5339, -0.2885],
        [ 1.7304, -0.4039,  0.4706,  0.6470,  0.9951],
        [ 1.0786, -0.9133,  0.9419, -0.0164,  1.1941],
        [ 0.3269, -1.5277,  0.1316, -1.0129,  0.5672],
        [ 0.3150,  0.9224, -0.4039,  1.6617,  0.8221]])

AutoGrad

In [28]:
x= torch.autograd.Variable(a)
y= torch.autograd.Variable(b,requires_grad=False)

nn module

In [29]:
input_num_units = 5
hidden_num_units = 20
output_num_units = 10

In [30]:
model = torch.nn.Sequential(
    torch.nn.Linear(input_num_units,hidden_num_units),
    torch.nn.ReLU(),
    torch.nn.Linear(hidden_num_units,output_num_units)
)

In [31]:
loss_fn = torch.nn.CrossEntropyLoss()

In [46]:
#Input array
X=np.array([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y=np.array([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
 return 1/(1 + np.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
 return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons))
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
  #Forward Propogation
  hidden_layer_input1=np.dot(X,wh)
  hidden_layer_input=hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1=np.dot(hiddenlayer_activations,wout)
  output_layer_input= output_layer_input1+ bout
  output = sigmoid(output_layer_input)

  #Backpropagation
  E = y-output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * slope_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T)
  d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) *lr
  bout += np.sum(d_output, axis=0,keepdims=True) *lr
  wh += X.T.dot(d_hiddenlayer) *lr
  bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr

print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 [[1]
 [1]
 [0]] 

predicted :
 [[ 0.97936216]
 [ 0.96623562]
 [ 0.04708524]]


In [44]:
X = torch.Tensor([[1,0,1,0],[1,0,1,1],[0,1,0,1]])

#Output
y = torch.Tensor([[1],[1],[0]])

#Sigmoid Function
def sigmoid (x):
  return 1/(1 + torch.exp(-x))

#Derivative of Sigmoid Function
def derivatives_sigmoid(x):
  return x * (1 - x)

#Variable initialization
epoch=5000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 3 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=torch.randn(inputlayer_neurons, hiddenlayer_neurons).type(torch.FloatTensor)
bh=torch.randn(1, hiddenlayer_neurons).type(torch.FloatTensor)
wout=torch.randn(hiddenlayer_neurons, output_neurons)
bout=torch.randn(1, output_neurons)

for i in range(epoch):

  #Forward Propogation
  hidden_layer_input1 = torch.mm(X, wh)
  hidden_layer_input = hidden_layer_input1 + bh
  hidden_layer_activations = sigmoid(hidden_layer_input)
 
  output_layer_input1 = torch.mm(hidden_layer_activations, wout)
  output_layer_input = output_layer_input1 + bout
  output = sigmoid(output_layer_input1)

  #Backpropagation
  E = y-output
  slope_output_layer = derivatives_sigmoid(output)
  slope_hidden_layer = derivatives_sigmoid(hidden_layer_activations)
  d_output = E * slope_output_layer
  Error_at_hidden_layer = torch.mm(d_output, wout.t())
  d_hiddenlayer = Error_at_hidden_layer * slope_hidden_layer
  wout += torch.mm(hidden_layer_activations.t(), d_output) *lr
  bout += d_output.sum() *lr
  wh += torch.mm(X.t(), d_hiddenlayer) *lr
  bh += d_output.sum() *lr
 
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 tensor([[1.],
        [1.],
        [0.]]) 

predicted :
 tensor([[0.9768],
        [0.9759],
        [0.0343]])
